import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const root = resolve(process.cwd());
const bundle = JSON.parse(readFileSync(resolve(root, "v2/generated/content.bundle.json"), "utf8"));
const cases = JSON.parse(readFileSync(resolve(root, "v2/reference/cases/manifest.json"), "utf8"));
const moduleCaseIds = new Set(cases.cases.filter((entry) => entry.id.startsWith("specialist-")).map((entry) => entry.id));
const coreCase = cases.cases.find((entry) => entry.id === "complete-core")?.id ?? "max-core";
const specialistCase = (moduleId) => `specialist-${moduleId}`;
const coverage = {
  contentFingerprint: bundle.metadata.contentFingerprint,
  coreItems: Object.fromEntries(bundle.items.filter((item) => item.role === "core" && item.status === "active").map((item) => [item.id, coreCase])),
  rootConstructs: Object.fromEntries(bundle.constructs.filter((construct) => construct.scope === "root").map((construct) => [construct.id, coreCase])),
  primaryProfiles: Object.fromEntries(bundle.profiles.map((profile) => [profile.id, coreCase])),
  modifiers: Object.fromEntries(bundle.modifiers.map((modifier) => [modifier.modifierId, coreCase])),
  specialistModules: Object.fromEntries(bundle.specialistModules.map((module) => [module.id, specialistCase(module.id)])),
  specialistItems: Object.fromEntries(bundle.items.filter((item) => item.role === "specialist" && item.status === "active").map((item) => [item.id, specialistCase(item.moduleId)])),
  specialistProfiles: Object.fromEntries(bundle.specialists.map((profile) => [profile.specialistId, specialistCase(profile.moduleId)])),
  ontologyNodes: Object.fromEntries(bundle.ontologyNodes.map((node) => [node.id, "content-validation"])),
  ontologyRelations: Object.fromEntries(bundle.ontologyRelations.map((relation) => [relation.id, "content-validation"])),
};
const lines = [
  "# v2 Reference Coverage", "",
  "Generated by `scripts/v2-reference/coverage.mjs` from the canonical bundle and replay manifest.", "",
  `- Content version: \`${bundle.metadata.contentVersion}\``,
  `- Content fingerprint: \`${bundle.metadata.contentFingerprint}\``,
  `- Replay cases: ${cases.cases.length}`,
  `- Full core fixture: \`${coreCase}\``,
  `- Specialist module fixtures: ${moduleCaseIds.size}`, "",
  "| Inventory | Total | Structural/exercised fixture |", "|---|---:|---|",
  `| Active core items | ${bundle.items.filter((item) => item.role === "core" && item.status === "active").length} | ${coreCase} |`,
  `| Root constructs | ${bundle.constructs.filter((construct) => construct.scope === "root").length} | ${coreCase} |`,
  `| Primary profiles | ${bundle.profiles.length} | ${coreCase} |`,
  `| Modifiers | ${bundle.modifiers.length} | ${coreCase} |`,
  `| Specialist modules | ${bundle.specialistModules.length} | one fixture per module |`,
  `| Specialist items | ${bundle.items.filter((item) => item.role === "specialist" && item.status === "active").length} | module fixtures |`,
  `| Specialist profiles | ${bundle.specialists.length} | module fixtures |`,
  `| Ontology nodes | ${bundle.ontologyNodes.length} | content validation |`,
  `| Ontology relations | ${bundle.ontologyRelations.length} | content validation |`, "",
  "All active content records have structural coverage. Scoring behavior is exercised by deterministic full-core and per-module cases; randomized coverage is separately fixed at seed `20260819` with 64 samples.", "",
];
writeFileSync(resolve(root, "docs/v2/reference-coverage.md"), `${lines.join("\n")}\n`);
writeFileSync(resolve(root, "v2/reference/reference-coverage.json"), `${JSON.stringify(coverage, null, 2)}\n`);
console.log(lines.join("\n"));
