import { createHash } from "node:crypto";
import { readFileSync, readdirSync, writeFileSync, unlinkSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { resolve } from "node:path";

const root = resolve(process.cwd());
const ledger = JSON.parse(readFileSync(resolve(root, "v2/reference/migration-behavior-ledger.json"), "utf8"));
const cases = JSON.parse(readFileSync(resolve(root, "v2/reference/cases/manifest.json"), "utf8"));
const bundle = JSON.parse(readFileSync(resolve(root, "v2/generated/content-manifest.json"), "utf8"));
const fixed = JSON.parse(readFileSync(resolve(root, "v2/reference/v1/manifest.json"), "utf8"));
const classifications = ["MUST_PRESERVE", "INTENTIONAL_CHANGE", "KNOWN_DEFECT", "RESEARCH_ONLY", "ARCHIVE_ONLY"];
const unresolved = ledger.behaviors.filter((behavior) => behavior.status !== "covered");
function treeFiles(directory) {
  return readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const absolute = resolve(directory, entry.name);
    if (entry.isDirectory()) return treeFiles(absolute);
    if (absolute.endsWith("/behavioral-release-receipt.json") || absolute.endsWith("/SHA256SUMS")) return [];
    return [absolute];
  });
}
const treeHash = createHash("sha256");
for (const file of treeFiles(resolve(root, "v2")).sort()) {
  treeHash.update(file.slice(root.length + 1));
  treeHash.update(readFileSync(file));
}
const repositoryHead = execFileSync("git", ["rev-parse", "HEAD"], { cwd: root, encoding: "utf8" }).trim();
const report = [
  "# Generated v2 Differential Report", "",
  "Generated by `scripts/v2-reference/report.mjs`. This report is a machine-derived gate summary, not a second scoring authority.", "",
  `- Gate status: **${unresolved.length === 0 ? "GO" : "NO-GO"}**`,
  `- Frozen v1 reference commit: \`${fixed.referenceCommit}\``,
  `- v2 content version: \`${bundle.contentVersion}\``,
  `- v2 content fingerprint: \`${bundle.contentFingerprint}\``,
  `- Replay cases: ${cases.cases.length}`,
  `- Behavior records: ${ledger.behaviors.length}`, "",
  "## Classification counts", "", "| Classification | Records | Covered |", "|---|---:|---:|",
  ...classifications.map((classification) => `| ${classification} | ${ledger.behaviors.filter((behavior) => behavior.classification === classification).length} | ${ledger.behaviors.filter((behavior) => behavior.classification === classification && behavior.status === "covered").length} |`), "",
  "## Required gate interpretation", "",
  "- MUST_PRESERVE records are required to be covered and pass their fixture assertions.",
  "- INTENTIONAL_CHANGE records require a declared v1 behavior, desired v2 behavior, fixture, and rationale.",
  "- KNOWN_DEFECT records are lockouts; reintroduction is a failure even if a legacy fixture would pass.",
  "- Unclassified scoring-relevant differences fail closed.", "", "## Unresolved records", "",
  unresolved.length === 0 ? "None." : unresolved.map((behavior) => `- ${behavior.id}: ${behavior.expectedV2}`).join("\n"), "", "## Fixture inventory", "",
  ...cases.cases.map((entry) => `- \`${entry.id}\`: ${entry.description}`), "",
];
writeFileSync(resolve(root, "docs/v2/generated/differential-report.md"), `${report.join("\n")}\n`);
const receipt = {
  schemaVersion: 1,
  status: unresolved.length === 0 ? "GO" : "NO-GO",
  frozenV1ReferenceCommit: fixed.referenceCommit,
  v2ContentVersion: bundle.contentVersion,
  v2ContentFingerprint: bundle.contentFingerprint,
  behaviorLedgerVersion: ledger.ledgerVersion,
  behaviorLedgerSha256: createHash("sha256").update(readFileSync(resolve(root, "v2/reference/migration-behavior-ledger.json"))).digest("hex"),
  referenceManifestSha256: createHash("sha256").update(readFileSync(resolve(root, "v2/reference/v1/manifest.json"))).digest("hex"),
  replayManifestSha256: createHash("sha256").update(readFileSync(resolve(root, "v2/reference/replay-manifest.json"))).digest("hex"),
  v2SourceTreeSha256: treeHash.digest("hex"),
  repositoryHead,
  workingTreeCommitStatus: "uncommitted-phase10-source",
  generatedAt: "2026-08-19",
  staleWhen: "Any change to v2 content, engine, contracts, reference cases, ledger, or version metadata requires regenerating this receipt.",
  noDeploymentClaim: true,
};
if (receipt.status === "GO") writeFileSync(resolve(root, "v2/reference/behavioral-release-receipt.json"), `${JSON.stringify(receipt, null, 2)}\n`);
else { try { unlinkSync(resolve(root, "v2/reference/behavioral-release-receipt.json")); } catch { /* no stale receipt */ } }
console.log(report.join("\n"));
