/**
 * Canonical authority for the clean ideology registry.
 *
 * This module has no dependency on the legacy data tree. The checked-in
 * canonical data is generated by the one-way development migration and is the
 * only runtime authority for the clean model.
 */

export type StableId = string;
export type CanonicalId = StableId;

export type ConceptualStatus = "canonical" | "provisional" | "deprecated";

/** Measurement lifecycle used by the canonical ontology. */
export type MeasurementStatus =
  | "unmeasured"
  | "candidate"
  | "validated"
  | "deprecated"
  | "not-started"
  | "catalog-only"
  | "research-candidate"
  | "experimental"
  | "compatibility-scored-unvalidated"
  | "respondent-supported-scored"
  | "validated-scoped-public"
  | "held"
  | "retired-alias";

export type PublicRoleStatus =
  | "primary"
  | "modifier"
  | "specialist"
  | "context"
  | "retired"
  | "internal";

export interface AuthorityStatus {
  readonly conceptualStatus: ConceptualStatus;
  readonly measurementStatus: MeasurementStatus;
  readonly publicRoleStatus: PublicRoleStatus;
}

export type CanonicalEntityKind =
  | "taxonomy"
  | "ontology"
  | "construct"
  | "facet"
  | "item"
  | "mapping"
  | "context";

export type ContextNamespace = "taxonomy" | "question";

export const CONTEXT_NAMESPACES: readonly ContextNamespace[] = [
  "taxonomy",
  "question",
] as const;

export interface CanonicalTaxonomy extends AuthorityStatus {
  readonly id: StableId;
  readonly name: string;
  readonly ontologyId?: StableId;
  readonly authorityKey?: string;
  readonly description?: string;
}

export interface CanonicalOntology extends AuthorityStatus {
  readonly id: StableId;
  readonly name: string;
  readonly authorityKey?: string;
  readonly description?: string;
}

export type RootConstructLayer = "normative" | "descriptive" | "prescriptive";

export interface CanonicalConstruct extends AuthorityStatus {
  readonly id: StableId;
  readonly name: string;
  readonly taxonomyId: StableId;
  readonly ontologyId?: StableId;
  readonly facetIds?: readonly StableId[];
  readonly authorityKey?: string;
  readonly description?: string;
  readonly layer?: RootConstructLayer;
  readonly negativePole?: string;
  readonly positivePole?: string;
}

export interface CanonicalFacet extends AuthorityStatus {
  readonly id: StableId;
  readonly name: string;
  readonly constructId: StableId;
  readonly authorityKey?: string;
  readonly description?: string;
}

export interface CanonicalStatementOption {
  readonly id: string;
  readonly text: string;
  /** Statement-choice mappings are root construct mappings as well. */
  readonly rootConstructWeights: Readonly<Record<StableId, number>>;
}

export type CanonicalItemRole = "core" | "specialist";

export interface CanonicalItem extends AuthorityStatus {
  readonly id: StableId;
  readonly prompt: string;
  readonly constructIds: readonly StableId[];
  /** Mappings copied from Question.axisWeights; keys must be root IDs. */
  readonly rootConstructWeights?: Readonly<Record<StableId, number>>;
  readonly facetIds?: readonly StableId[];
  readonly contextRefs?: readonly ContextReference[];
  readonly authorityKey?: string;
  readonly role?: CanonicalItemRole;
  readonly layer?: RootConstructLayer;
  readonly domain?: string;
  readonly responseType?: string;
  readonly tier?: string;
  readonly moduleId?: StableId;
  readonly localConstructWeights?: Readonly<Record<StableId, number>>;
  readonly statementOptions?: readonly CanonicalStatementOption[];
  readonly sources?: readonly {
    readonly title: string;
    readonly url: string;
    readonly publisher?: string;
    readonly publishedAt?: string;
  }[];
  readonly helpText?: string;
  readonly contextNote?: string;
  readonly evidenceNote?: string;
  readonly explanation?: string;
  readonly confidencePrompt?: string;
  readonly priorityPrompt?: string;
  readonly allowDontKnow?: boolean;
  readonly reverseScored?: boolean;
  readonly reviewStatus?: string;
  readonly sourceStatus?: string;
  readonly textHash?: string;
}

/** Relations supported by the vNext ontology and compatibility graph. */
export type MappingRelation =
  | "measures"
  | "supports"
  | "contrasts"
  | "composes"
  | "aliases"
  | "subtype_of"
  | "family_member_of"
  | "hybrid_of"
  | "configures"
  | "requires"
  | "overlaps_with"
  | "contrasts_with"
  | "often_combines_with"
  | "regional_variant_of"
  | "historical_predecessor_of"
  | "influenced_by"
  | "institutionalizes"
  | "context_for"
  | "policy_expression_of"
  | "alias_of"
  | "not_equivalent_to"
  | "incompatible_with_core";

export type CanonicalReferenceKind = CanonicalEntityKind | "node";
export interface CanonicalReference {
  readonly kind: CanonicalReferenceKind;
  readonly id: StableId;
}

export interface CanonicalMapping extends AuthorityStatus {
  readonly id: StableId;
  readonly source: CanonicalReference;
  readonly target: CanonicalReference;
  readonly relation: MappingRelation;
  readonly weight?: number;
  readonly contextRefs?: readonly ContextReference[];
  readonly authorityKey?: string;
}

export interface CanonicalRelation extends AuthorityStatus {
  readonly id: StableId;
  readonly source: CanonicalReference;
  readonly target: CanonicalReference;
  readonly relation: MappingRelation;
  readonly note?: string;
  readonly graphVersion?: string;
  readonly provenance?: readonly string[];
}

export interface ContextReference {
  readonly namespace: ContextNamespace;
  readonly id: StableId;
}

export interface CanonicalContext extends AuthorityStatus {
  readonly id: StableId;
  readonly namespace: ContextNamespace;
  readonly label?: string;
  readonly ownerId?: StableId;
  readonly authorityKey?: string;
  readonly description?: string;
}

export interface CanonicalContexts {
  readonly taxonomy: readonly CanonicalContext[];
  readonly question: readonly CanonicalContext[];
}

export type IdeologyConceptualKind =
  | "family-anchor"
  | "broad-tradition"
  | "compound-tradition"
  | "bridge-tradition"
  | "hybrid-configuration"
  | "cross-cutting-orientation"
  | "subtype-tradition"
  | "regional-historical-variant"
  | "institutional-project"
  | "strategy-or-program"
  | "regime-or-authoritarian-project"
  | "intellectual-current"
  | "discourse-frame"
  | "policy-proposal"
  | "governance-model"
  | "historical-reference"
  | "speculative-technological-current";

export interface IdeologyNode extends AuthorityStatus {
  readonly id: StableId;
  readonly canonicalName: string;
  readonly aliases?: readonly string[];
  readonly conceptualKind: IdeologyConceptualKind;
  readonly secondaryKinds?: readonly IdeologyConceptualKind[];
  readonly canonicalDefinition: string;
  readonly boundaryStatement?: string;
  readonly layerRelevance?: readonly RootConstructLayer[];
  readonly historicalScope?: string;
  readonly geographicScope?: string;
  readonly family?: string;
  readonly subfamily?: string;
  readonly parentId?: StableId;
  readonly legacyDisposition?: string;
  readonly legacyComponents?: readonly StableId[];
  readonly graphRelations?: readonly CanonicalRelation[];
  readonly version: string;
  readonly description?: string;
  readonly cautionNote?: string;
  readonly usageNote?: string;
  readonly sources?: readonly {
    readonly title: string;
    readonly url: string;
    readonly publisher?: string;
  }[];
}

export interface ProductionScoringProfile {
  readonly id: StableId;
  readonly nodeId: StableId;
  readonly labelId: StableId;
  readonly version: string;
  readonly rootConstructIds: readonly StableId[];
  readonly centroid: Readonly<Record<StableId, number>>;
  readonly requiredRootConstructIds: readonly StableId[];
  readonly minimumItemCounts?: Readonly<Record<StableId, number>>;
  readonly status: MeasurementStatus;
  readonly rationale?: string;
}

export type ModifierAvailability =
  | "core-construct"
  | "focused-follow-up"
  | "catalog-only";

export interface ModifierIndicator {
  readonly questionId: StableId;
  readonly direction: 1 | -1;
  readonly rationale: string;
}

export interface ModifierContract {
  readonly id: StableId;
  readonly nodeId: StableId;
  readonly labelId: StableId;
  readonly availability: ModifierAvailability;
  readonly constructName: string;
  readonly note: string;
  readonly indicators?: readonly ModifierIndicator[];
  readonly minimumAnsweredItems?: number;
}

export interface SpecialistCandidate {
  readonly id: StableId;
  readonly nodeId?: StableId;
  readonly moduleId: StableId;
  readonly name: string;
  readonly description: string;
  readonly status: string;
  readonly variant?: string;
  readonly signals?: Readonly<Record<StableId, number>>;
  readonly gates?: readonly Readonly<Record<string, string | number>>[];
}

export interface SpecialistModule {
  readonly id: StableId;
  readonly version: string;
  readonly title: string;
  readonly shortTitle: string;
  readonly description: string;
  readonly invitationNote: string;
  readonly estimatedMinutes: number;
  readonly itemIds: readonly StableId[];
  readonly constructIds: readonly StableId[];
  readonly candidateIds: readonly StableId[];
}

export interface CanonicalManifestCounts {
  readonly roots: number;
  readonly primary: number;
  readonly specialist: number;
  readonly modifier: number;
  readonly context: number;
  readonly retired: number;
  readonly modules: number;
  readonly activeCoreItems: number;
  readonly conditionalSpecialistItems: number;
}

export interface CanonicalManifestMetadata {
  readonly schemaVersion: string;
  readonly version: string;
  readonly fingerprint: string | null;
  readonly sourceCommit?: string;
  readonly methodologyCommit?: string;
  readonly counts?: CanonicalManifestCounts;
}

export interface CanonicalManifest {
  readonly metadata: CanonicalManifestMetadata;
  readonly taxonomy: readonly CanonicalTaxonomy[];
  readonly ontology: readonly CanonicalOntology[];
  readonly constructs: readonly CanonicalConstruct[];
  readonly facets: readonly CanonicalFacet[];
  readonly items: readonly CanonicalItem[];
  readonly mappings: readonly CanonicalMapping[];
  readonly contexts: CanonicalContexts;
  /** Canonical vNext ideology records. */
  readonly nodes?: readonly IdeologyNode[];
  readonly relations?: readonly CanonicalRelation[];
  readonly productionProfiles?: readonly ProductionScoringProfile[];
  readonly modifierContracts?: readonly ModifierContract[];
  readonly specialistModules?: readonly SpecialistModule[];
  readonly specialistCandidates?: readonly SpecialistCandidate[];
  readonly activeCoreItemIds?: readonly StableId[];
  readonly conditionalSpecialistItemIds?: readonly StableId[];
}

export const CANONICAL_MANIFEST_SCHEMA_VERSION = "canonical-domain-v2";
export const CANONICAL_MANIFEST_VERSION = "ideology-registry-2026-08-clean-v1";

function deepFreeze<T>(value: T): T {
  if (value === null || typeof value !== "object") return value;
  Object.freeze(value);
  for (const nested of Object.values(value as Record<string, unknown>)) {
    deepFreeze(nested);
  }
  return value;
}

import { CANONICAL_DATA } from "./canonicalData";
const canonicalNodes = CANONICAL_DATA.nodes?.map((node) => ({
  ...node,
  publicRoleStatus: node.publicRoleView,
}));

const DRAFT_MANIFEST: CanonicalManifest = {
  metadata: CANONICAL_DATA.metadata,
  taxonomy: CANONICAL_DATA.taxonomy,
  ontology: CANONICAL_DATA.ontology,
  constructs: CANONICAL_DATA.constructs,
  facets: CANONICAL_DATA.facets,
  items: CANONICAL_DATA.items,
  mappings: CANONICAL_DATA.mappings,
  contexts: CANONICAL_DATA.contexts,
  nodes: canonicalNodes,
  relations: CANONICAL_DATA.relations,
  productionProfiles: CANONICAL_DATA.productionProfiles,
  modifierContracts: CANONICAL_DATA.modifierContracts,
  specialistModules: CANONICAL_DATA.specialistModules,
  specialistCandidates: CANONICAL_DATA.specialistCandidates,
  activeCoreItemIds: CANONICAL_DATA.activeCoreItemIds,
  conditionalSpecialistItemIds: CANONICAL_DATA.conditionalSpecialistItemIds,
};

/** The sole clean-rebuild manifest authority. */
export const CANONICAL_MANIFEST: CanonicalManifest = deepFreeze(DRAFT_MANIFEST);
export const canonicalManifest = CANONICAL_MANIFEST;
/** Payload hashed for the deterministic manifest fingerprint (self-reference omitted). */
export function canonicalManifestFingerprintInput(
  manifest: CanonicalManifest = CANONICAL_MANIFEST,
): Omit<CanonicalManifest, "metadata"> & {
  readonly metadata: Omit<CanonicalManifestMetadata, "fingerprint">;
} {
  const { fingerprint: _fingerprint, ...metadata } = manifest.metadata;
  const { metadata: _manifestMetadata, ...payload } = manifest;
  void _fingerprint;
  void _manifestMetadata;
  return { metadata, ...payload };
}

/** SHA-256 of canonical-json-v1 bytes for canonicalManifestFingerprintInput. */
export const CANONICAL_MANIFEST_FINGERPRINT =
  CANONICAL_MANIFEST.metadata.fingerprint;
/** Frozen inventory counts for release and migration gates. */
export const CANONICAL_COUNTS = CANONICAL_MANIFEST.metadata.counts!;
